2021-10-05 16:02:54.8499 ERROR Something went wrong inside CreateMedicine action: Object reference not set to an instance of an object.
2021-10-05 16:03:43.8996 INFO Returned User.
2021-10-05 16:05:24.8665 ERROR Something went wrong inside CreateMedicine action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 16:08:06.0531 INFO Returned User.
2021-10-05 16:08:22.7247 ERROR Something went wrong inside CreateMedicine action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 16:10:14.4290 ERROR Something went wrong inside CreateMedicine action: Object reference not set to an instance of an object.
2021-10-05 16:10:19.5259 INFO Returned User.
2021-10-05 16:10:55.9095 INFO Returned all Resources_Request from database.
2021-10-05 16:11:28.8039 INFO Returned User.
2021-10-05 16:11:53.3178 INFO Returned User.
2021-10-05 16:11:55.0849 INFO Returned User.
2021-10-05 16:11:56.2132 INFO Returned User.
2021-10-05 16:12:16.5227 INFO Returned User.
2021-10-05 16:12:20.3072 INFO Returned all Resources_Request from database.
2021-10-05 16:15:49.7578 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Missing type map configuration or unsupported mapping.

Mapping types:
Resources_Request -> Resource_RequestForUpdateDto
Entities.Models.Resources_Request -> Entities.DataTransferObjects.Resources_Request___Dto.Resource_RequestForUpdateDto
2021-10-05 16:17:20.5088 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Value cannot be null. (Parameter 'patchDoc')
2021-10-05 16:18:39.5368 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Value cannot be null. (Parameter 'patchDoc')
2021-10-05 16:20:14.3668 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Value cannot be null. (Parameter 'patchDoc')
2021-10-05 16:20:40.2745 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Value cannot be null. (Parameter 'patchDoc')
2021-10-05 16:25:57.6000 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Value cannot be null. (Parameter 'patchDoc')
2021-10-05 16:26:23.7990 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Value cannot be null. (Parameter 'patchDoc')
2021-10-05 16:30:02.8230 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: Value cannot be null. (Parameter 'patchDoc')
2021-10-05 16:47:18.2254 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 16:48:09.1309 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 16:49:44.0064 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 16:51:59.1647 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 16:53:56.2568 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 17:07:24.6800 ERROR Something went wrong inside UpdatePartialEmegencyDisaster action: The instance of entity type 'Resources_Materials' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2021-10-05 17:19:31.1793 INFO Returned User.
2021-10-05 17:19:33.7277 INFO Returned all Resources_Request from database.
